name: deploy-dev

on: 
  push:
    branches:
      - dev
      

jobs:
  deploy_aws:
    runs-on: ubuntu-latest

    steps:
      - name: Add private key
        run: |
          mkdir -p ~/.ssh
          echo "${{secrets.SSH_PRIVATE_KEY_NEW}}" 1> ~/.ssh/aws_key
          chmod 700 ~/.ssh/aws_key

      - name: Login -> dev server
        run: |
          ssh ubuntu@44.211.144.128 -o StrictHostKeyChecking=no -i ~/.ssh/aws_key -t 'ls'

        


