name: gopal

on: 
  push:
    branches:
      - main

jobs:
  test1:
    runs-on: ubuntu-lastes 

    steps:
      - name: Checkout code
        uses : actions/checkout@v4

      - name: cd code
        run: cd week17 && ls

